🔧 (ci.yml): improve turborepo cache check and add debug logs ⬆️ (package.json): specify yarn package manager version
Enhance the turborepo cache check for the Android build by adding debug logs and handling empty or invalid output. This helps in diagnosing issues with the cache status. Additionally, specify the yarn package manager version in package.json to ensure consistency across different environments.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,10 +68,23 @@ jobs:
 
       - name: Check turborepo cache for Android
         run: |
-          TURBO_CACHE_STATUS=$(node -p "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).tasks.find(t => t.task === 'build:android').cache.status" <<< "$(yarn --silent turbo run build:android --cache-dir='${{ env.TURBO_CACHE_DIR }}' --dry=json)")
+          echo "Running Turbo Dry Run for Android Build"
+          TURBO_OUTPUT=$(yarn --silent turbo run build:android --cache-dir='${{ env.TURBO_CACHE_DIR }}' --dry=json)
+
+          # 출력 내용 확인
+          echo "Turbo Output: $TURBO_OUTPUT" # 디버깅을 위한 임시 로그
+
+          if [[ -z "$TURBO_OUTPUT" ]]; then
+            echo "Turbo output is empty or invalid"
+            exit 1
+          fi
+
+          TURBO_CACHE_STATUS=$(node -p "JSON.parse('$TURBO_OUTPUT').tasks.find(t => t.task === 'build:android')?.cache?.status")
 
           if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
             echo "turbo_cache_hit=1" >> $GITHUB_ENV
+          else
+            echo "Turbo cache miss or invalid status"
           fi
         shell: bash
 
